/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 50
#define YY_END_OF_BUFFER 51
static yyconst short int yy_accept[462] =
    {   0,
        0,    0,   51,   50,   48,   49,   50,   50,   30,   31,
       28,   26,   24,   27,   29,   18,   20,   22,   23,   36,
       41,   37,   45,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   32,   33,   44,
       34,   43,   35,   50,   48,   49,   40,   21,    0,   18,
       18,   18,   18,   20,   25,   42,   38,   39,   19,   19,
       19,   19,   19,   19,   19,    1,   19,   19,   19,   19,
       19,   19,   19,   19,    0,   47,   46,    0,   18,   18,
       18,   19,   19,   19,   19,   12,   19,    6,    7,   13,
       19,   19,   19,    2,   19,   19,   18,   18,   18,   18,

       19,   19,    8,    9,    5,   19,   16,   19,   19,   19,
       18,   18,   18,   18,   18,   19,   10,   19,   19,   19,
        4,   14,   18,   18,   18,   18,   18,   18,   19,   19,
       17,   19,   19,   18,   18,   18,   18,   18,   18,   18,
       19,    3,   11,   15,   18,   18,   18,   18,   18,   18,
       18,   18,   19,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   19,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   19,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   19,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   19,   18,

       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   19,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   19,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       19,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   19,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   18,   18,

       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   19,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       19,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   19,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,

       18,   18,   18,   18,   18,   18,   18,   19,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   19,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   19,   18,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    1,    1,    6,
        7,    8,    9,   10,   11,    1,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
       18,   19,   20,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   30,   31,   32,   33,   34,   35,
       30,   36,   37,   38,   30,   39,   40,   30,   41,   30,
       42,    1,   43,   44,    1,    1,   30,   30,   30,   30,

       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   45,   30,   30,   30,   30,   30,
       30,   30,   46,   47,   48,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       49,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,   50,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[51] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    4,    4,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    1,    1,    5,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[789] =
    {   0,
        0,    0,  862,  863,  859,  857,  841,  853,  863,  863,
      863,  863,  863,  863,  863,   38,   40,  842,  863,   44,
      863,  838,  863,  819,  820,  825,  823,  820,  816,    0,
       30,  815,  812,  822,  805,  824,   29,  863,  863,  863,
      796,  863,  863,  794,  840,  838,  863,  863,  186,   45,
       47,    0,   53,   55,  863,  863,  863,  863,    0,  148,
      147,  158,  139,  140,  140,    0,  137,  149,  137,  148,
      132,  129,  134,  132,  111,  863,  863,   57,    0,    0,
       59,    0,  137,  126,  120,    0,  129,    0,    0,    0,
      125,  122,  119,    0,   95,   81,    0,    0,    0,   61,

        0,   76,    0,    0,    0,   75,   78,   83,   80,   78,
        0,    0,    0,    0,   63,    0,    0,   80,   66,   72,
        0,   60,    0,    0,    0,    0,    0,   65,    0,   52,
        0,   56,   31,    0,    0,    0,    0,    0,    0,   67,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   73,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   75,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   80,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   82,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  100,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  102,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  108,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  110,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  115,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  117,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  119,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  121,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  123,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  125,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  127,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,  129,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  135,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  137,  863,  863,
      863,  180,  182,  184,  189,  191,  193,  195,  197,  199,
      201,  203,  205,  207,  209,  211,  213,  215,  217,  219,
      221,  223,  225,  227,  229,  231,  233,  235,  237,  239,
      241,  243,  245,  247,  249,  251,  253,  255,  257,  259,

      261,  263,  265,  267,  269,  271,  273,  275,  277,  279,
      281,  283,  285,  287,  289,  291,  293,  295,  297,  299,
      301,  303,  305,  307,  309,  311,  313,  315,  317,  319,
      321,  323,  325,  327,  329,  331,  333,  335,  337,  339,
      341,  343,  345,  347,  349,  351,  353,  355,  357,  359,
      361,  363,  365,  367,  369,  371,  373,  375,  377,  379,
      381,  383,  385,  387,  389,  391,  393,  395,  397,  399,
      401,  403,  405,  407,  409,  411,  413,  415,  417,  419,
      421,  423,  425,  427,  429,  431,  433,  435,  437,  439,
      441,  443,  445,  447,  449,  451,  453,  455,  457,  459,

      461,  463,  465,  467,  469,  471,  473,  475,  477,  479,
      481,  483,  485,  487,  489,  491,  493,  495,  497,  499,
      501,  503,  505,  507,  509,  511,  513,  515,  517,  519,
      521,  523,  525,  527,  529,  531,  533,  535,  537,  539,
      541,  543,  545,  547,  549,  551,  553,  555,  557,  559,
      561,  563,  565,  567,  569,  571,  573,  575,  577,  579,
      581,  583,  585,  587,  589,  591,  593,  595,  597,  599,
      601,  603,  605,  607,  609,  611,  613,  615,  617,  619,
      621,  623,  625,  627,  629,  631,  633,  635,  637,  639,
      641,  643,  645,  647,  649,  651,  653,  655,  657,  659,

      661,  663,  665,  667,  669,  671,  673,  675,  677,  679,
      681,  683,  685,  687,  689,  691,  693,  695,  697,  699,
      701,  703,  705,  707,  709,  711,  713,  715,  717,  719,
      721,  723,  725,  727,  729,  731,  733,  735,  737,  739,
      741,  743,  745,  747,  749,  751,  753,  755,  757,  759,
      761,  763,  765,  767,  769,  771,  773,  775,  777,  779,
      781,  783,  785,  787,  789,  791,  793,  795,  797,  799,
      801,  803,  805,  807,  809,  811,  813,  815,  817,  819,
      821,  823,  825,  827,  829,  831,  833,  835
    } ;

static yyconst short int yy_def[789] =
    {   0,
      461,    1,  461,  461,  461,  461,  461,  462,  461,  461,
      461,  461,  461,  461,  461,  463,  463,  461,  461,  461,
      461,  461,  461,  464,  464,  464,  464,  464,  464,  464,
      464,  464,  464,  464,  464,  464,  464,  461,  461,  461,
      465,  461,  461,  461,  461,  461,  461,  461,  462,  463,
      463,  466,  467,  463,  461,  461,  461,  461,  468,  468,
      468,  468,  468,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  468,  468,  465,  461,  461,  463,  469,  470,
      471,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  473,  474,  475,  476,

      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      478,  479,  480,  481,  482,  483,  483,  483,  483,  483,
      483,  483,  484,  485,  486,  487,  488,  489,  490,  490,
      490,  490,  490,  491,  492,  493,  494,  495,  496,  497,
      498,  498,  498,  498,  499,  500,  501,  502,  503,  504,
      505,  506,  507,  508,  509,  510,  511,  512,  513,  514,
      515,  516,  517,  518,  519,  520,  521,  522,  523,  524,
      525,  526,  527,  528,  529,  530,  531,  532,  533,  534,
      535,  536,  537,  538,  539,  540,  541,  542,  543,  544,
      545,  546,  547,  548,  549,  550,  551,  552,  553,  554,

      555,  556,  557,  558,  559,  560,  561,  562,  563,  564,
      565,  566,  567,  568,  569,  570,  571,  572,  573,  574,
      575,  576,  577,  578,  579,  580,  581,  582,  583,  584,
      585,  586,  587,  588,  589,  590,  591,  592,  593,  594,
      595,  596,  597,  598,  599,  600,  601,  602,  603,  604,
      605,  606,  607,  608,  609,  610,  611,  612,  613,  614,
      615,  616,  617,  618,  619,  620,  621,  622,  623,  624,
      625,  626,  627,  628,  629,  630,  631,  632,  633,  634,
      635,  636,  637,  638,  639,  640,  641,  642,  643,  644,
      645,  646,  647,  648,  649,  650,  651,  652,  653,  654,

      655,  656,  657,  658,  659,  660,  661,  662,  663,  664,
      665,  666,  667,  668,  669,  670,  671,  672,  673,  674,
      675,  676,  677,  678,  679,  680,  681,  682,  683,  684,
      685,  686,  687,  688,  689,  690,  691,  692,  693,  694,
      695,  696,  697,  698,  699,  700,  701,  702,  703,  704,
      705,  706,  707,  708,  709,  710,  711,  712,  713,  714,
      715,  716,  717,  718,  719,  720,  721,  722,  723,  724,
      725,  726,  727,  728,  729,  730,  731,  732,  733,  734,
      735,  736,  737,  738,  739,  740,  741,  742,  743,  744,
      745,  746,  747,  748,  749,  750,  751,  752,  753,  754,

      755,  756,  757,  758,  759,  760,  761,  762,  763,  764,
      765,  766,  767,  768,  769,  770,  771,  772,  773,  774,
      775,  776,  777,  778,  779,  780,  781,  782,  783,  784,
      785,  786,  787,  788,  763,  764,  765,  766,  767,  768,
      769,  770,  771,  772,  773,  774,  775,  776,  777,  778,
      779,  780,  781,  782,  783,  784,  785,  786,  461,  461,
        0,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,

      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,

      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,

      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461
    } ;

static yyconst short int yy_nxt[914] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   30,   31,   30,
       30,   32,   30,   30,   33,   34,   30,   35,   36,   37,
       30,   38,   39,   40,   30,   41,   42,   43,    4,   44,
       50,   51,   54,   54,   56,   66,   73,   50,   51,   78,
       51,   57,   67,  144,   74,   79,   79,   54,   54,   78,
       78,   98,   98,  113,  113,  126,  126,  138,  138,  150,
      150,  143,   53,  142,   53,  160,  160,  171,  171,   53,
      133,   53,  183,  183,  196,  196,  132,   81,  131,   53,

      130,   53,  122,  100,  121,  115,  120,  128,  119,  140,
      118,  152,  210,  210,  225,  225,  117,  162,  110,  173,
      241,  241,  258,  258,  185,  109,  198,  276,  276,  295,
      295,  315,  315,  336,  336,  358,  358,  381,  381,  405,
      405,  430,  430,  108,  212,  107,  227,  456,  456,  456,
      456,  106,  243,  105,  260,  104,  103,  102,   76,  278,
       96,  297,   95,  317,   94,  338,   93,  360,   92,  383,
       91,  407,   90,  432,   89,   88,   87,   86,   85,  458,
       84,  458,   49,   83,   49,   52,   52,   59,   59,   75,
       48,   75,   75,   75,   79,   79,   80,   80,   82,   82,

       97,   97,   98,   98,   99,   99,  101,  101,  111,  111,
      112,  112,  113,  113,  114,  114,  116,  116,  123,  123,
      124,  124,  125,  125,  126,  126,  127,  127,  129,  129,
      134,  134,  135,  135,  136,  136,  137,  137,  138,  138,
      139,  139,  141,  141,  145,  145,  146,  146,  147,  147,
      148,  148,  149,  149,  150,  150,  151,  151,  153,  153,
      154,  154,  155,  155,  156,  156,  157,  157,  158,  158,
      159,  159,  160,  160,  161,  161,  163,  163,  164,  164,
      165,  165,  166,  166,  167,  167,  168,  168,  169,  169,
      170,  170,  171,  171,  172,  172,  174,  174,  175,  175,

      176,  176,  177,  177,  178,  178,  179,  179,  180,  180,
      181,  181,  182,  182,  183,  183,  184,  184,  186,  186,
      187,  187,  188,  188,  189,  189,  190,  190,  191,  191,
      192,  192,  193,  193,  194,  194,  195,  195,  196,  196,
      197,  197,  199,  199,  200,  200,  201,  201,  202,  202,
      203,  203,  204,  204,  205,  205,  206,  206,  207,  207,
      208,  208,  209,  209,  210,  210,  211,  211,  213,  213,
      214,  214,  215,  215,  216,  216,  217,  217,  218,  218,
      219,  219,  220,  220,  221,  221,  222,  222,  223,  223,
      224,  224,  225,  225,  226,  226,  228,  228,  229,  229,

      230,  230,  231,  231,  232,  232,  233,  233,  234,  234,
      235,  235,  236,  236,  237,  237,  238,  238,  239,  239,
      240,  240,  241,  241,  242,  242,  244,  244,  245,  245,
      246,  246,  247,  247,  248,  248,  249,  249,  250,  250,
      251,  251,  252,  252,  253,  253,  254,  254,  255,  255,
      256,  256,  257,  257,  258,  258,  259,  259,  261,  261,
      262,  262,  263,  263,  264,  264,  265,  265,  266,  266,
      267,  267,  268,  268,  269,  269,  270,  270,  271,  271,
      272,  272,  273,  273,  274,  274,  275,  275,  276,  276,
      277,  277,  279,  279,  280,  280,  281,  281,  282,  282,

      283,  283,  284,  284,  285,  285,  286,  286,  287,  287,
      288,  288,  289,  289,  290,  290,  291,  291,  292,  292,
      293,  293,  294,  294,  295,  295,  296,  296,  298,  298,
      299,  299,  300,  300,  301,  301,  302,  302,  303,  303,
      304,  304,  305,  305,  306,  306,  307,  307,  308,  308,
      309,  309,  310,  310,  311,  311,  312,  312,  313,  313,
      314,  314,  315,  315,  316,  316,  318,  318,  319,  319,
      320,  320,  321,  321,  322,  322,  323,  323,  324,  324,
      325,  325,  326,  326,  327,  327,  328,  328,  329,  329,
      330,  330,  331,  331,  332,  332,  333,  333,  334,  334,

      335,  335,  336,  336,  337,  337,  339,  339,  340,  340,
      341,  341,  342,  342,  343,  343,  344,  344,  345,  345,
      346,  346,  347,  347,  348,  348,  349,  349,  350,  350,
      351,  351,  352,  352,  353,  353,  354,  354,  355,  355,
      356,  356,  357,  357,  358,  358,  359,  359,  361,  361,
      362,  362,  363,  363,  364,  364,  365,  365,  366,  366,
      367,  367,  368,  368,  369,  369,  370,  370,  371,  371,
      372,  372,  373,  373,  374,  374,  375,  375,  376,  376,
      377,  377,  378,  378,  379,  379,  380,  380,  381,  381,
      382,  382,  384,  384,  385,  385,  386,  386,  387,  387,

      388,  388,  389,  389,  390,  390,  391,  391,  392,  392,
      393,  393,  394,  394,  395,  395,  396,  396,  397,  397,
      398,  398,  399,  399,  400,  400,  401,  401,  402,  402,
      403,  403,  404,  404,  405,  405,  406,  406,  408,  408,
      409,  409,  410,  410,  411,  411,  412,  412,  413,  413,
      414,  414,  415,  415,  416,  416,  417,  417,  418,  418,
      419,  419,  420,  420,  421,  421,  422,  422,  423,  423,
      424,  424,  425,  425,  426,  426,  427,  427,  428,  428,
      429,  429,  430,  430,  431,  431,  433,  433,  434,  434,
      435,  435,  436,  436,  437,  437,  438,  438,  439,  439,

      440,  440,  441,  441,  442,  442,  443,  443,  444,  444,
      445,  445,  446,  446,  447,  447,  448,  448,  449,  449,
      450,  450,  451,  451,  452,  452,  453,  453,  454,  454,
      455,  455,  456,  456,  457,  457,  459,  459,  460,  460,
       46,   45,   77,   76,   72,   71,   70,   69,   68,   65,
       64,   63,   62,   61,   60,   58,   55,   48,   47,   46,
       45,  461,    3,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,

      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461
    } ;

static yyconst short int yy_chk[914] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       16,   16,   17,   17,   20,   31,   37,   50,   50,   51,
       51,   20,   31,  133,   37,   53,   53,   54,   54,   78,
       78,   81,   81,  100,  100,  115,  115,  128,  128,  140,
      140,  132,   16,  130,   17,  152,  152,  162,  162,   50,
      122,   51,  173,  173,  185,  185,  120,   53,  119,   54,

      118,   78,  110,   81,  109,  100,  108,  115,  107,  128,
      106,  140,  198,  198,  212,  212,  102,  152,   96,  162,
      227,  227,  243,  243,  173,   95,  185,  260,  260,  278,
      278,  297,  297,  317,  317,  338,  338,  360,  360,  383,
      383,  407,  407,   93,  198,   92,  212,  432,  432,  458,
      458,   91,  227,   87,  243,   85,   84,   83,   75,  260,
       74,  278,   73,  297,   72,  317,   71,  338,   70,  360,
       69,  383,   68,  407,   67,   65,   64,   63,   62,  432,
       61,  458,  462,   60,  462,  463,  463,  464,  464,  465,
       49,  465,  465,  465,  466,  466,  467,  467,  468,  468,

      469,  469,  470,  470,  471,  471,  472,  472,  473,  473,
      474,  474,  475,  475,  476,  476,  477,  477,  478,  478,
      479,  479,  480,  480,  481,  481,  482,  482,  483,  483,
      484,  484,  485,  485,  486,  486,  487,  487,  488,  488,
      489,  489,  490,  490,  491,  491,  492,  492,  493,  493,
      494,  494,  495,  495,  496,  496,  497,  497,  498,  498,
      499,  499,  500,  500,  501,  501,  502,  502,  503,  503,
      504,  504,  505,  505,  506,  506,  507,  507,  508,  508,
      509,  509,  510,  510,  511,  511,  512,  512,  513,  513,
      514,  514,  515,  515,  516,  516,  517,  517,  518,  518,

      519,  519,  520,  520,  521,  521,  522,  522,  523,  523,
      524,  524,  525,  525,  526,  526,  527,  527,  528,  528,
      529,  529,  530,  530,  531,  531,  532,  532,  533,  533,
      534,  534,  535,  535,  536,  536,  537,  537,  538,  538,
      539,  539,  540,  540,  541,  541,  542,  542,  543,  543,
      544,  544,  545,  545,  546,  546,  547,  547,  548,  548,
      549,  549,  550,  550,  551,  551,  552,  552,  553,  553,
      554,  554,  555,  555,  556,  556,  557,  557,  558,  558,
      559,  559,  560,  560,  561,  561,  562,  562,  563,  563,
      564,  564,  565,  565,  566,  566,  567,  567,  568,  568,

      569,  569,  570,  570,  571,  571,  572,  572,  573,  573,
      574,  574,  575,  575,  576,  576,  577,  577,  578,  578,
      579,  579,  580,  580,  581,  581,  582,  582,  583,  583,
      584,  584,  585,  585,  586,  586,  587,  587,  588,  588,
      589,  589,  590,  590,  591,  591,  592,  592,  593,  593,
      594,  594,  595,  595,  596,  596,  597,  597,  598,  598,
      599,  599,  600,  600,  601,  601,  602,  602,  603,  603,
      604,  604,  605,  605,  606,  606,  607,  607,  608,  608,
      609,  609,  610,  610,  611,  611,  612,  612,  613,  613,
      614,  614,  615,  615,  616,  616,  617,  617,  618,  618,

      619,  619,  620,  620,  621,  621,  622,  622,  623,  623,
      624,  624,  625,  625,  626,  626,  627,  627,  628,  628,
      629,  629,  630,  630,  631,  631,  632,  632,  633,  633,
      634,  634,  635,  635,  636,  636,  637,  637,  638,  638,
      639,  639,  640,  640,  641,  641,  642,  642,  643,  643,
      644,  644,  645,  645,  646,  646,  647,  647,  648,  648,
      649,  649,  650,  650,  651,  651,  652,  652,  653,  653,
      654,  654,  655,  655,  656,  656,  657,  657,  658,  658,
      659,  659,  660,  660,  661,  661,  662,  662,  663,  663,
      664,  664,  665,  665,  666,  666,  667,  667,  668,  668,

      669,  669,  670,  670,  671,  671,  672,  672,  673,  673,
      674,  674,  675,  675,  676,  676,  677,  677,  678,  678,
      679,  679,  680,  680,  681,  681,  682,  682,  683,  683,
      684,  684,  685,  685,  686,  686,  687,  687,  688,  688,
      689,  689,  690,  690,  691,  691,  692,  692,  693,  693,
      694,  694,  695,  695,  696,  696,  697,  697,  698,  698,
      699,  699,  700,  700,  701,  701,  702,  702,  703,  703,
      704,  704,  705,  705,  706,  706,  707,  707,  708,  708,
      709,  709,  710,  710,  711,  711,  712,  712,  713,  713,
      714,  714,  715,  715,  716,  716,  717,  717,  718,  718,

      719,  719,  720,  720,  721,  721,  722,  722,  723,  723,
      724,  724,  725,  725,  726,  726,  727,  727,  728,  728,
      729,  729,  730,  730,  731,  731,  732,  732,  733,  733,
      734,  734,  735,  735,  736,  736,  737,  737,  738,  738,
      739,  739,  740,  740,  741,  741,  742,  742,  743,  743,
      744,  744,  745,  745,  746,  746,  747,  747,  748,  748,
      749,  749,  750,  750,  751,  751,  752,  752,  753,  753,
      754,  754,  755,  755,  756,  756,  757,  757,  758,  758,
      759,  759,  760,  760,  761,  761,  762,  762,  763,  763,
      764,  764,  765,  765,  766,  766,  767,  767,  768,  768,

      769,  769,  770,  770,  771,  771,  772,  772,  773,  773,
      774,  774,  775,  775,  776,  776,  777,  777,  778,  778,
      779,  779,  780,  780,  781,  781,  782,  782,  783,  783,
      784,  784,  785,  785,  786,  786,  787,  787,  788,  788,
       46,   45,   44,   41,   36,   35,   34,   33,   32,   29,
       28,   27,   26,   25,   24,   22,   18,    8,    7,    6,
        5,    3,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,

      461,  461,  461,  461,  461,  461,  461,  461,  461,  461,
      461,  461,  461
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "specification.lxi"
#define INITIAL 0
#line 2 "specification.lxi"
    #include <math.h>
    #include <stdio.h>
    #include "scanner.h"

    int lines = 0;
#line 799 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 17 "specification.lxi"


#line 964 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 462 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 863 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 19 "specification.lxi"
{printf("Keyword : %s\n", yytext); return IF;}               
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 20 "specification.lxi"
{printf("Keyword : %s\n", yytext); return VAR;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 21 "specification.lxi"
{printf("Keyword : %s\n", yytext); return PROGRAM;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 22 "specification.lxi"
{printf("Keyword : %s\n", yytext); return WHILE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 23 "specification.lxi"
{printf("Keyword : %s\n", yytext); return ELSE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 24 "specification.lxi"
{printf("Keyword : %s\n", yytext); return FOR;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 25 "specification.lxi"
{printf("Keyword : %s\n", yytext); return INT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 26 "specification.lxi"
{printf("Keyword : %s\n", yytext); return BOOL;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 27 "specification.lxi"
{printf("Keyword : %s\n", yytext); return CHAR;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 28 "specification.lxi"
{printf("Keyword : %s\n", yytext); return ARRAY;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 29 "specification.lxi"
{printf("Keyword : %s\n", yytext); return TYPEDEF;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 30 "specification.lxi"
{printf("Keyword : %s\n", yytext); return DIV;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 31 "specification.lxi"
{printf("Keyword : %s\n", yytext); return MOD;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 32 "specification.lxi"
{printf("Keyword : %s\n", yytext); return WRITE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 33 "specification.lxi"
{printf("Keyword : %s\n", yytext); return WRITELN;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 34 "specification.lxi"
{printf("Keyword : %s\n", yytext); return READ;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 35 "specification.lxi"
{printf("Keyword : %s\n", yytext); return READLN;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 37 "specification.lxi"
{printf( "Lexical error at: %s\n ", yytext ); return ERROR;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 38 "specification.lxi"
{printf( "Identifier: %s\n", yytext ); return IDENTIFIER;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 39 "specification.lxi"
{printf( "Number: %s\n", yytext); return NUMBER;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 40 "specification.lxi"
{printf( "Word: %s\n", yytext); return WORD;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 42 "specification.lxi"
{printf( "Separator: %s\n", yytext ); return COLON;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 43 "specification.lxi"
{printf( "Separator: %s\n", yytext ); return SEMI_COLON;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 44 "specification.lxi"
{printf( "Separator: %s\n", yytext ); return COMA;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 45 "specification.lxi"
{printf( "Separator: %s\n", yytext ); return DOTS;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 46 "specification.lxi"
{printf( "Operator: %s\n", yytext ); return PLUS;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 47 "specification.lxi"
{printf( "Operator: %s\n", yytext ); return MINUS;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 48 "specification.lxi"
{printf( "Operator: %s\n", yytext ); return MULTIPLY;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 49 "specification.lxi"
{printf( "Operator: %s\n", yytext ); return DIVISION;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 50 "specification.lxi"
{printf( "Separator: %s\n", yytext ); return OPEN_ROUND_PARENTHESIS;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 51 "specification.lxi"
{printf( "Separator: %s\n", yytext ); return CLOSE_ROUND_PARENTHESIS;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 52 "specification.lxi"
{printf( "Separator: %s\n", yytext ); return OPEN_SQUARE_PARENTHESIS;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 53 "specification.lxi"
{printf( "Separator: %s\n", yytext ); return CLOSE_SQUARE_PARENTHESIS;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 54 "specification.lxi"
{printf( "Separator: %s\n", yytext ); return OPEN_CURLY_PARENTHESIS;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 55 "specification.lxi"
{printf( "Separator: %s\n", yytext ); return CLOSE_CURLY_PARENTHESIS;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 56 "specification.lxi"
{printf( "Operator: %s\n", yytext ); return LESS_THAN;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 "specification.lxi"
{printf( "Operator: %s\n", yytext ); return GREATER_THAN;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 "specification.lxi"
{printf( "Operator: %s\n", yytext ); return LESS_OR_EQUAL_THAN;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 "specification.lxi"
{printf( "Operator: %s\n", yytext ); return GREATER_OR_EQUAL_THAN;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 60 "specification.lxi"
{printf( "Operator: %s\n", yytext ); return DIFFERENT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 61 "specification.lxi"
{printf( "Operator: %s\n", yytext ); return EQUAL;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 62 "specification.lxi"
{printf( "Operator: %s\n", yytext ); return ASSIGNMENT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 63 "specification.lxi"
{printf( "Separator: %s\n", yytext ); return BAR;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 64 "specification.lxi"
{printf( "Operator: %s\n", yytext); return POW;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 65 "specification.lxi"
{printf( "Operator: %s\n", yytext); return QUESTION_MARK;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 66 "specification.lxi"
{printf( "Operator: %s\n", yytext); return EPSILON;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 68 "specification.lxi"
{}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 69 "specification.lxi"
{}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 70 "specification.lxi"
{++lines;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 72 "specification.lxi"
ECHO;
	YY_BREAK
#line 1297 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 462 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 462 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 461);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 72 "specification.lxi"
