#define CONST 0
#define IDENTIFIER 1
#define IF 2
#define VAR 3
#define EPSILON 4
#define WHILE 5
#define MOD 6
#define DIV 7
#define ARRAY 8
#define ELSE 9
#define TYPEDEF 10
#define BOOL 11
#define INT 12
#define CHAR 13
#define DOUBLE 14
#define FOR 15
#define WRITE 16
#define WRITELN 17
#define READ 18
#define READLN 19

#define COLON 20
#define SEMI_COLON 21
#define OPEN_ROUND_PARENTHESIS 22
#define CLOSE_ROUND_PARENTHESIS 23
#define OPEN_SQUARE_PARENTHESIS 24
#define CLOSE_SQUARE_PARENTHESIS 25
#define OPEN_CURLY_PARENTHESIS 26
#define CLOSE_CURLY_PARENTHESIS 27
#define MULTIPLY 28
#define DIVISION 29
#define PLUS 30
#define MINUS 31
#define COMA 32
#define POW 33
#define ASSIGNMENT 34
#define QUESTION_MARK 35
#define LESS_THAN 36
#define GREATER_THAN 37
#define LESS_OR_EQUAL_THAN 38
#define GREATER_OR_EQUAL_THAN 39
#define EQUAL 40
#define DIFFERENT 41
#define BAR 42
#define PROGRAM 43
#define DOTS 44